# Generated by Django 3.0.2 on 2020-03-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewMatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('nature_of_matter', models.TextField()),
                ('price_estimate', models.IntegerField()),
                ('contact_person', models.CharField(max_length=250)),
            ],
        ),
    ]
