# Generated by Django 3.0.2 on 2020-03-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmatter',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='newmatter',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='newmatter',
            name='reference_number',
            field=models.CharField(default='cliqo4321', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CollaboratorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliqo.NewMatter', to_field='reference_number', verbose_name='matter reference')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.CharField(max_length=200)),
                ('contact_address', models.TextField()),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliqo.NewMatter', to_field='reference_number', verbose_name='matter reference')),
            ],
        ),
    ]
