# Generated by Django 3.0.2 on 2020-03-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0002_auto_20200302_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmatter',
            name='hourly_rate',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='newmatter',
            name='reference_number',
            field=models.CharField(default='#REF0000', max_length=100, unique=True),
        ),
    ]
