# Generated by Django 3.0.2 on 2020-03-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0004_auto_20200303_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboratorinfo',
            name='ref',
        ),
        migrations.AddField(
            model_name='newmatter',
            name='client_name',
            field=models.CharField(default='Client Name', max_length=250),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='collaborator_email',
            field=models.EmailField(default='collab@domain.com', max_length=254),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='collaborator_full_name',
            field=models.CharField(default='Collaborator Name', max_length=250),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='collaborator_phone_number',
            field=models.CharField(default='+27123456789', max_length=20),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='collaborator_role',
            field=models.CharField(default='Collaborator Role', max_length=150),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='contact_address',
            field=models.TextField(default='Contact Address'),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='contact_email',
            field=models.EmailField(default='contact@domain.com', max_length=254),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='contact_name',
            field=models.CharField(default='Contact Name', max_length=250),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='contact_phone',
            field=models.CharField(default='+27123456789', max_length=20),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='matter_goal',
            field=models.CharField(default='Ensure that ...', max_length=250),
        ),
        migrations.DeleteModel(
            name='ClientInfo',
        ),
        migrations.DeleteModel(
            name='CollaboratorInfo',
        ),
    ]
