# Generated by Django 3.0.2 on 2020-03-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0005_auto_20200304_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmatter',
            name='nature_of_matter',
            field=models.TextField(default='Nature of Matter'),
        ),
        migrations.AlterField(
            model_name='newmatter',
            name='price_estimate',
            field=models.IntegerField(default=100),
        ),
    ]
