# Generated by Django 3.0.2 on 2020-03-04 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0006_auto_20200304_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmatter',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='newmatter',
            name='collaborator_email',
        ),
        migrations.RemoveField(
            model_name='newmatter',
            name='collaborator_full_name',
        ),
        migrations.RemoveField(
            model_name='newmatter',
            name='collaborator_phone_number',
        ),
        migrations.RemoveField(
            model_name='newmatter',
            name='collaborator_role',
        ),
        migrations.RemoveField(
            model_name='newmatter',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='newmatter',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='newmatter',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='newmatter',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='newmatter',
            name='matter_goal',
        ),
        migrations.CreateModel(
            name='Outcomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(default='Ensure that ...', max_length=250)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliqo.NewMatter', to_field='reference_number', verbose_name='matter reference')),
            ],
        ),
        migrations.CreateModel(
            name='CollaboratorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Collaborator Name', max_length=250)),
                ('phone_number', models.CharField(default='+27123456789', max_length=20)),
                ('role', models.CharField(default='Collaborator Role', max_length=150)),
                ('email', models.EmailField(default='collab@domain.com', max_length=254)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliqo.NewMatter', to_field='reference_number', verbose_name='matter reference')),
            ],
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='Client Name', max_length=250)),
                ('contact_name', models.CharField(default='Contact Name', max_length=250)),
                ('contact_phone', models.CharField(default='+27123456789', max_length=20)),
                ('contact_email', models.EmailField(default='contact@domain.com', max_length=254)),
                ('contact_address', models.TextField(default='Contact Address')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliqo.NewMatter', to_field='reference_number', verbose_name='matter reference')),
            ],
        ),
    ]
