# Generated by Django 3.0.2 on 2020-03-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0007_auto_20200304_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmatter',
            name='client_name',
            field=models.CharField(default='Client Name', max_length=250),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='contact_address',
            field=models.TextField(default='Contact Address'),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='contact_email',
            field=models.EmailField(default='contact@domain.com', max_length=254),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='contact_name',
            field=models.CharField(default='Contact Name', max_length=250),
        ),
        migrations.AddField(
            model_name='newmatter',
            name='contact_phone',
            field=models.CharField(default='+27123456789', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClientInfo',
        ),
    ]
