# Generated by Django 3.0.2 on 2020-03-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0008_auto_20200304_0938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Outcomes',
            new_name='Outcome',
        ),
    ]
