# Generated by Django 3.0.2 on 2020-03-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0010_auto_20200304_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmatter',
            name='hour_estimate',
            field=models.IntegerField(default=1),
        ),
    ]
