# Generated by Django 3.0.2 on 2020-03-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0011_newmatter_hour_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='Task', max_length=250)),
                ('billing', models.CharField(choices=[('Billable', 'Billable'), ('Non-billable', 'Non-billable')], default='Billable', max_length=12)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliqo.NewMatter', to_field='reference_number', verbose_name='Reference Number')),
            ],
        ),
        migrations.RemoveField(
            model_name='newcontact',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='ref',
        ),
        migrations.AddField(
            model_name='newclient',
            name='contact_address',
            field=models.TextField(default='Contact Address'),
        ),
        migrations.AddField(
            model_name='newclient',
            name='contact_email',
            field=models.EmailField(default='contact@domain.com', max_length=254),
        ),
        migrations.AddField(
            model_name='newclient',
            name='contact_name',
            field=models.CharField(default='Contact Name', max_length=250),
        ),
        migrations.AddField(
            model_name='newclient',
            name='contact_phone',
            field=models.CharField(default='+27123456789', max_length=20),
        ),
        migrations.DeleteModel(
            name='CollaboratorInfo',
        ),
        migrations.DeleteModel(
            name='NewContact',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
    ]
