# Generated by Django 3.0.2 on 2020-03-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0013_auto_20200306_1935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewClient',
            new_name='NewContact',
        ),
    ]
