# Generated by Django 3.0.3 on 2020-03-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0015_auto_20200308_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
