# Generated by Django 3.0.3 on 2020-03-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0016_delete_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
