# Generated by Django 3.0.3 on 2020-03-10 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0016_delete_demo'),
        ('todo', '0011_auto_20190724_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bill_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='billing',
            field=models.CharField(choices=[('Billable', 'Billable'), ('Non-billable', 'Non-billable')], default='Billable', max_length=12),
        ),
        migrations.AddField(
            model_name='task',
            name='ref',
            field=models.ForeignKey(default='REF01234', on_delete=django.db.models.deletion.CASCADE, to='cliqo.NewMatter', to_field='reference_number', verbose_name='Reference Number'),
        ),
    ]
