# Generated by Django 3.0.3 on 2020-03-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliqo', '0016_delete_demo'),
        ('todo', '0013_auto_20200310_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reference_number',
        ),
        migrations.AddField(
            model_name='task',
            name='ref',
            field=models.ForeignKey(blank=True, default='REF01234', on_delete=django.db.models.deletion.CASCADE, to='cliqo.NewMatter', to_field='reference_number', verbose_name='Reference Number'),
        ),
    ]
