# Generated by Django 3.0.3 on 2020-03-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_remove_task_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bill_amount',
        ),
        migrations.RemoveField(
            model_name='task',
            name='billing',
        ),
    ]
