# Generated by Django 3.0.3 on 2020-03-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20200310_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bill_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='billing',
            field=models.CharField(choices=[('Billable', 'Billable'), ('Non-billable', 'Non-billable')], default='Billable', max_length=12),
        ),
        migrations.AddField(
            model_name='task',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
