# Generated by Django 3.0.3 on 2020-03-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20200310_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
